---
- name: Tomcat deployment playbook
  hosts: tomcat-nodes
  become: yes
  become_method: sudo
  remote_user: root
  vars:
    tomcat_ver: 9.0.33
    ui_manager_user: manageruser
    ui_manager_pass: managerpassword
    ui_admin_username: adminuser
    ui_admin_pass: adminpassword
  roles:
    - tomcat
